"""Report and agent-prompt rendering."""

from __future__ import annotations

import hashlib
import html
import json
import re
from pathlib import Path
from typing import Iterable

from . import __version__
from .models import CommentCluster, ReviewPlan, WorkSlice


def write_reports(plan: ReviewPlan, out_dir: Path, formats: Iterable[str]) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    requested = set(formats)
    if "all" in requested:
        requested = {"markdown", "json", "junit", "sarif", "prompts"}
    outputs = {}
    if "markdown" in requested or "md" in requested:
        path = out_dir / "review-plan.md"
        write_text(path, render_markdown(plan))
        outputs["markdown"] = str(path)
    if "json" in requested:
        path = out_dir / "review-plan.json"
        write_json(path, plan.to_dict())
        outputs["json"] = str(path)
    if "junit" in requested:
        path = out_dir / "junit.xml"
        write_text(path, render_junit(plan))
        outputs["junit"] = str(path)
    if "sarif" in requested:
        path = out_dir / "review-plan.sarif"
        write_text(path, render_sarif(plan))
        outputs["sarif"] = str(path)
    if "prompts" in requested:
        prompt_outputs = write_agent_prompts(plan, out_dir / "agent-prompts")
        outputs["prompts"] = str(out_dir / "agent-prompts" / "index.md")
        outputs.update(prompt_outputs)
    return outputs


def render_markdown(plan: ReviewPlan) -> str:
    summary = plan.to_dict()["summary"]
    lines = [
        "# Agent Review Comment Plan",
        "",
        f"- Input comments: {summary['input_count']}",
        f"- Open comments: {summary['open_count']}",
        f"- Clusters: {summary['cluster_count']}",
        f"- Work slices: {summary['slice_count']}",
        f"- Duplicate ratio: {summary['duplicate_ratio']}",
        f"- Untriaged ratio: {summary['untriaged_ratio']}",
        f"- Gate passed: {'yes' if plan.gate_passed else 'no'}",
        "",
        "## Work Slices",
        "",
        "| Slice | Severity | Score | Category | Files | Title |",
        "| --- | --- | ---: | --- | ---: | --- |",
    ]
    if not plan.slices:
        lines.append("| - | info | 0 | none | 0 | No open review comments. |")
    for work_slice in plan.slices:
        lines.append(
            f"| {work_slice.id} | {work_slice.severity} | {work_slice.score} | {work_slice.category} | "
            f"{len(work_slice.files)} | {escape_pipe(work_slice.title)} |"
        )
    lines.extend(["", "## Clusters", "", "| Cluster | Severity | Duplicates | Category | Files | Comment |", "| --- | --- | ---: | --- | --- | --- |"])
    if not plan.clusters:
        lines.append("| - | info | 0 | none | - | No clusters. |")
    for cluster in plan.clusters:
        files = ", ".join(cluster.files) if cluster.files else "-"
        lines.append(f"| {cluster.id} | {cluster.severity} | {cluster.duplicate_count} | {cluster.category} | `{escape_pipe(files)}` | {escape_pipe(cluster.title)} |")
    if plan.warnings:
        lines.extend(["", "## Gate Warnings", ""])
        for warning in plan.warnings:
            lines.append(f"- {warning}")
    lines.extend(["", "## Agent Checklists", ""])
    for work_slice in plan.slices:
        lines.append(f"### {work_slice.id} {work_slice.title}")
        lines.append("")
        for item in work_slice.checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_junit(plan: ReviewPlan) -> str:
    failures = plan.warnings
    tests = max(1, len(plan.slices) + len(plan.warnings))
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<testsuite name="agent-review-comment-slicer" tests="{tests}" failures="{len(failures)}">',
    ]
    if not plan.slices and not plan.warnings:
        lines.append('  <testcase classname="agent_review_comment_slicer" name="no_open_comments" />')
    for work_slice in plan.slices:
        lines.append(f'  <testcase classname="agent_review_comment_slicer.slice" name="{html.escape(work_slice.id)}" />')
    for index, warning in enumerate(plan.warnings, start=1):
        lines.append(f'  <testcase classname="agent_review_comment_slicer.gate" name="warning_{index}">')
        lines.append(f'    <failure message="{html.escape(warning)}" type="gate">{html.escape(warning)}</failure>')
        lines.append("  </testcase>")
    lines.append("</testsuite>")
    return "\n".join(lines) + "\n"


def render_sarif(plan: ReviewPlan) -> str:
    rules = []
    for category in sorted({cluster.category for cluster in plan.clusters} | {"gate"}):
        rules.append(
            {
                "id": f"review.{category}",
                "name": f"Review comment: {category}",
                "shortDescription": {"text": f"Deduplicated review comment cluster in category {category}."},
                "fullDescription": {
                    "text": "Generated by agent-review-comment-slicer from exported PR/code review comments."
                },
                "helpUri": "https://github.com/yanqr213/agent-review-comment-slicer#readme",
            }
        )

    results = [sarif_result_for_cluster(cluster) for cluster in plan.clusters]
    for index, warning in enumerate(plan.warnings, start=1):
        results.append(
            {
                "ruleId": "review.gate",
                "level": "error",
                "message": {"text": warning},
                "partialFingerprints": {"primaryLocationLineHash": stable_hash(f"gate:{warning}")},
                "properties": {"kind": "gate", "warningIndex": index},
            }
        )

    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "agent-review-comment-slicer",
                        "semanticVersion": __version__,
                        "informationUri": "https://github.com/yanqr213/agent-review-comment-slicer",
                        "rules": rules,
                    }
                },
                "results": results,
                "properties": {
                    "summary": plan.to_dict()["summary"],
                    "reportFormat": "agent-review-comment-slicer.sarif",
                },
            }
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def sarif_result_for_cluster(cluster: CommentCluster) -> dict:
    primary = first_located_comment(cluster)
    result = {
        "ruleId": f"review.{cluster.category}",
        "level": sarif_level(cluster.severity),
        "message": {"text": f"{cluster.id}: {cluster.title}"},
        "partialFingerprints": {"primaryLocationLineHash": stable_hash(cluster_fingerprint(cluster))},
        "properties": {
            "category": cluster.category,
            "clusterId": cluster.id,
            "commentCount": len(cluster.comments),
            "duplicateCount": cluster.duplicate_count,
            "owner": cluster.owner,
            "score": cluster.score,
            "severity": cluster.severity,
        },
    }
    if primary and primary.path:
        location = {
            "physicalLocation": {
                "artifactLocation": {"uri": primary.path.replace("\\", "/")},
                "region": {"startLine": primary.line or 1},
            }
        }
        result["locations"] = [location]
    return result


def first_located_comment(cluster: CommentCluster):
    for comment in cluster.comments:
        if comment.path:
            return comment
    return cluster.comments[0] if cluster.comments else None


def sarif_level(severity: str) -> str:
    if severity in {"blocker", "high"}:
        return "error"
    if severity == "medium":
        return "warning"
    return "note"


def cluster_fingerprint(cluster: CommentCluster) -> str:
    files = ",".join(cluster.files)
    return f"{cluster.category}|{cluster.severity}|{files}|{cluster.title}"


def stable_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:32]


def write_agent_prompts(plan: ReviewPlan, prompt_dir: Path) -> dict:
    prompt_dir.mkdir(parents=True, exist_ok=True)
    outputs = {}
    index_path = prompt_dir / "index.md"
    write_text(index_path, render_prompt_index(plan))
    for work_slice in plan.slices:
        path = prompt_dir / f"{safe_filename(work_slice.id)}.md"
        write_text(path, render_agent_prompt(plan, work_slice))
        outputs[f"prompt:{work_slice.id}"] = str(path)
    return outputs


def render_prompt_index(plan: ReviewPlan) -> str:
    summary = plan.to_dict()["summary"]
    lines = [
        "# Agent Review Fix Prompts",
        "",
        f"- Open comments: {summary['open_count']}",
        f"- Clusters: {summary['cluster_count']}",
        f"- Work slices: {summary['slice_count']}",
        f"- Gate passed: {'yes' if plan.gate_passed else 'no'}",
        "",
        "Use one prompt file per agent session. Each prompt is scoped to one review slice.",
        "",
        "| Prompt | Severity | Category | Score | Files | Title |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    if not plan.slices:
        lines.append("| - | info | none | 0 | 0 | No open review comments. |")
    for work_slice in plan.slices:
        lines.append(
            f"| `{safe_filename(work_slice.id)}.md` | {work_slice.severity} | {work_slice.category} | "
            f"{work_slice.score} | {len(work_slice.files)} | {escape_pipe(work_slice.title)} |"
        )
    if plan.warnings:
        lines.extend(["", "## Gate Warnings", ""])
        for warning in plan.warnings:
            lines.append(f"- {warning}")
    return "\n".join(lines).rstrip() + "\n"


def render_agent_prompt(plan: ReviewPlan, work_slice: WorkSlice) -> str:
    lines = [
        f"# Review Fix Prompt: {work_slice.id}",
        "",
        "You are an AI coding agent assigned to resolve one focused code review slice. Verify the current repository state before editing, preserve unrelated user changes, and keep the fix limited to the files and comments below.",
        "",
        "## Slice Summary",
        "",
        f"- Title: {work_slice.title}",
        f"- Severity: {work_slice.severity}",
        f"- Category: {work_slice.category}",
        f"- Owner: {work_slice.owner}",
        f"- Score: {work_slice.score}",
        f"- Gate currently passed: {'yes' if plan.gate_passed else 'no'}",
        "",
        "## Files",
        "",
    ]
    if work_slice.files:
        for path in work_slice.files:
            lines.append(f"- `{path}`")
    else:
        lines.append("- No file path was provided; inspect the comments and ask for clarification if the target file cannot be inferred.")
    lines.extend(["", "## Checklist", ""])
    for item in work_slice.checklist:
        lines.append(f"- [ ] {item}")
    lines.extend(["", "## Review Comments", ""])
    for cluster in work_slice.clusters:
        lines.extend(
            [
                f"### {cluster.id}: {cluster.title}",
                "",
                f"- Severity: {cluster.severity}",
                f"- Category: {cluster.category}",
                f"- Reason: {cluster.reason}",
                "",
            ]
        )
        for comment in cluster.comments:
            location = comment.path or "unassigned file"
            if comment.line:
                location = f"{location}:{comment.line}"
            lines.append(f"- `{comment.id}` at `{location}` by {comment.author or 'unknown'}: {one_line(comment.body)}")
            if comment.suggestion:
                lines.append(f"  Suggested fix: {one_line(comment.suggestion)}")
            if comment.url:
                lines.append(f"  URL: {comment.url}")
        lines.append("")
    lines.extend(
        [
            "## Completion Rules",
            "",
            "- Fix the underlying issue, not only the visible symptom.",
            "- Add or update tests when the comment asks for behavior, safety, or regression coverage.",
            "- Re-run the narrowest relevant validation first, then the broader project validation if available.",
            "- Leave a short handoff note listing changed files, validation run, unresolved comments, and residual risks.",
            "- Do not close, hide, or mark review comments resolved from this prompt alone; let the reviewer or CI confirm.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def safe_filename(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "-", value.strip())
    return cleaned or "slice"


def one_line(value: str) -> str:
    return " ".join(str(value).split())


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False, sort_keys=True)
        handle.write("\n")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def escape_pipe(value: str) -> str:
    return str(value).replace("|", "\\|")
